# Generated by Django 6.1.1 on 2026-09-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Libro')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('categoria', models.CharField(choices=[('TECNOLOGIA', 'Tecnología e Informática'), ('NARRATIVA', 'Narrativa y Literatura'), ('CIENCIA', 'Ciencias Exactas y Naturales'), ('HISTORIA', 'Historia y Ciencias Sociales')], max_length=50, verbose_name='Categoría')),
                ('precio_prestamo', models.IntegerField(verbose_name='Precio Préstamo ($ CLP)')),
                ('stock_copias', models.IntegerField(verbose_name='Copias Disponibles')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
            ],
        ),
    ]
